/**
 * Op-based template editing + the local invariants the server does NOT check.
 *
 * Why ops instead of "read the whole definition, write the whole definition":
 * a template is 25–65 KB of JSON, so a full read-modify-write round trip costs
 * an agent ~40k tokens and invites whole-document corruption. Ops touch one
 * element at a time and print a diff.
 *
 * Why local invariants: the PUT boundary runs ReportDefinitionValidator, which
 * catches structural violations — but NOT the four Report Studio footguns below.
 * Each is silent at save time and only shows up as "my element vanished":
 *
 *   1. elements written to the deprecated `page.elements` (renderer ignores it)
 *   2. 3-level fieldKey (renders from sample JSON, never DB-bindable)
 *   3. unknown / retired element type (label, table)
 *   4. schema keys outside the explicit Zod object (stripped on import)
 *
 * Structural validation itself stays server-side — no Ajv here, keeping the CLI
 * dependency-free.
 */
import { readFileSync, existsSync } from 'node:fs'
import { randomUUID } from 'node:crypto'
import { fileURLToPath } from 'node:url'
import { join, dirname } from 'node:path'

/** Marker that identifies the repo root — the generated schemas live beside it. */
const ROOT_MARKER = join('schemas', 'element-types.json')

/**
 * Locate the repo root by walking up from every plausible starting point.
 *
 * Deliberately not `new URL('../../..', import.meta.url)`: vitest serves modules
 * over a non-file URL, so a URL-relative resolve breaks under test while working
 * fine when the CLI is spawned normally. Searching upward works in both.
 */
function findRepoRoot() {
  const starts = []
  if (import.meta.url?.startsWith('file:')) starts.push(dirname(fileURLToPath(import.meta.url)))
  starts.push(process.cwd())
  for (const start of starts) {
    let dir = start
    for (let i = 0; i < 8; i++) {
      if (existsSync(join(dir, ROOT_MARKER))) return dir
      const parent = dirname(dir)
      if (parent === dir) break
      dir = parent
    }
  }
  throw new Error(`${ROOT_MARKER} が見つかりません。リポジトリ内から実行してください。`)
}

const REPO_ROOT = findRepoRoot()

function readRepoJson(relative) {
  return JSON.parse(readFileSync(join(REPO_ROOT, relative), 'utf8'))
}

// Single source of truth for both: generated by `npm run generate:schema`.
const ELEMENT_TYPES = new Set(readRepoJson('schemas/element-types.json').elementTypes)
const DB_IDENTIFIER_RE = new RegExp(readRepoJson('schemas/shared-constants.json').dbIdentifierPattern)

/** Retired types and what they became (ElementRenderer auto-migrates on load). */
const RETIRED_TYPES = { label: 'text', table: 'formTable' }

// Explicit (non-passthrough) Zod object keys — anything else is stripped on import.
const SCHEMA_FIELD_KEYS = new Set(['id', 'key', 'label', 'type', 'itemType', 'dbColumnName', 'computed', 'expression'])
const SCHEMA_GROUP_KEYS = new Set(['id', 'label', 'role', 'dataKey', 'fields', 'tableMeta', 'linkedMasterGroupId'])
const TABLE_META_KEYS = new Set(['namespace', 'tableName'])

const PAPER_PRESETS = {
  A4P: { width: 210, height: 297 },
  A4L: { width: 297, height: 210 },
  A3P: { width: 297, height: 420 },
  A3L: { width: 420, height: 297 },
}

export class OpsError extends Error {
  constructor(errors) {
    super(errors.join('\n  '))
    this.name = 'OpsError'
    this.errors = errors
  }
}

// ── helpers ────────────────────────────────────────────────────────────────

function allSections(definition) {
  const list = []
  for (const [pageIndex, page] of (definition.pages ?? []).entries()) {
    for (const section of page.sections ?? []) list.push({ pageIndex, page, section })
  }
  return list
}

function findElement(definition, id) {
  for (const { pageIndex, section } of allSections(definition)) {
    const idx = (section.elements ?? []).findIndex((e) => e.id === id)
    if (idx >= 0) return { pageIndex, section, index: idx, element: section.elements[idx] }
  }
  return null
}

/** Accept both the canonical shape and flat x/y/width/height convenience input. */
function normalizeElement(input) {
  const {
    x, y, width, height, position, size, id, zIndex, locked, visible, style, ...rest
  } = input
  return {
    id: id ?? randomUUID(),
    ...rest,
    position: position ?? { x: Number(x ?? 0), y: Number(y ?? 0) },
    size: size ?? { width: Number(width ?? 40), height: Number(height ?? 8) },
    zIndex: zIndex ?? 1,
    locked: locked ?? false,
    visible: visible ?? true,
    style: style ?? {},
  }
}

/** RFC 6901 JSON Pointer set. Returns an error string, or null on success. */
function setPointer(root, pointer, value) {
  if (typeof pointer !== 'string' || !pointer.startsWith('/')) {
    return `pointer は "/" 始まりの JSON Pointer である必要があります: ${pointer}`
  }
  const parts = pointer
    .slice(1)
    .split('/')
    .map((p) => p.replace(/~1/g, '/').replace(/~0/g, '~'))
  let node = root
  for (let i = 0; i < parts.length - 1; i++) {
    const key = Array.isArray(node) ? Number(parts[i]) : parts[i]
    if (node == null || typeof node !== 'object' || !(key in node)) {
      return `pointer の経路が存在しません: ${pointer}（${parts[i]} で失敗）`
    }
    node = node[key]
  }
  const last = Array.isArray(node) ? Number(parts[parts.length - 1]) : parts[parts.length - 1]
  if (node == null || typeof node !== 'object') return `pointer の親がオブジェクトではありません: ${pointer}`
  node[last] = value
  return null
}

// ── invariants ─────────────────────────────────────────────────────────────

/**
 * The four footguns the server does not catch, plus identifier shape.
 * @returns {{errors: string[], warnings: string[]}}
 */
export function checkInvariants(definition) {
  const errors = []
  const warnings = []

  // 1. deprecated page.elements
  for (const [i, page] of (definition.pages ?? []).entries()) {
    const n = Array.isArray(page?.elements) ? page.elements.length : 0
    if (n > 0) {
      errors.push(
        `page[${i}].elements に ${n} 件あります。@deprecated でレンダラーに無視されます — ` +
          `page[${i}].sections[N].elements へ移してください。`,
      )
    }
  }

  for (const { pageIndex, section } of allSections(definition)) {
    for (const el of section.elements ?? []) {
      const where = `page[${pageIndex}]/${section.sectionType ?? '?'}/${el.id ?? '(no id)'}`

      // 3. element type
      if (!ELEMENT_TYPES.has(el.type)) {
        const replacement = RETIRED_TYPES[el.type]
        errors.push(
          replacement
            ? `${where}: 要素型 "${el.type}" は廃止されました。"${replacement}" を使ってください。`
            : `${where}: 未知の要素型 "${el.type}"（schemas/element-types.json に存在しません）。`,
        )
      }

      // 2. schema path depth
      if (typeof el.fieldKey === 'string' && el.fieldKey.split('.').length > 2) {
        errors.push(
          `${where}: fieldKey "${el.fieldKey}" は3階層です。スキーマパスは dataKey.fieldKey の2階層まで — ` +
            'buildFlatDataFromResolved が data[dataKey] にしか置かないため DB バインドできません。',
        )
      }
    }
  }

  // 4. Zod strip — keys outside the explicit object are dropped at the import boundary
  for (const group of definition?.schema?.groups ?? []) {
    const gWhere = `schema.${group.dataKey ?? '(no dataKey)'}`
    for (const key of Object.keys(group)) {
      if (!SCHEMA_GROUP_KEYS.has(key)) {
        warnings.push(`${gWhere}: "${key}" は SchemaGroupSchema に無いため import 時に除去されます。`)
      }
    }
    if (group.dataKey !== undefined && !DB_IDENTIFIER_RE.test(group.dataKey)) {
      errors.push(`${gWhere}: dataKey は ${DB_IDENTIFIER_RE.source} に一致する必要があります。`)
    }
    for (const key of Object.keys(group.tableMeta ?? {})) {
      if (!TABLE_META_KEYS.has(key)) {
        warnings.push(`${gWhere}.tableMeta: "${key}" は import 時に除去されます。`)
      }
    }
    for (const field of group.fields ?? []) {
      const fWhere = `${gWhere}.${field.key ?? '(no key)'}`
      for (const key of Object.keys(field)) {
        if (!SCHEMA_FIELD_KEYS.has(key)) {
          warnings.push(`${fWhere}: "${key}" は SchemaFieldSchema に無いため import 時に除去されます。`)
        }
      }
      if (field.key !== undefined && !DB_IDENTIFIER_RE.test(field.key)) {
        errors.push(`${fWhere}: フィールドキーは ${DB_IDENTIFIER_RE.source} に一致する必要があります。`)
      }
    }
  }

  return { errors, warnings }
}

// ── op application ─────────────────────────────────────────────────────────

/**
 * Apply ops to `definition` in place.
 *
 * @param definition mutable ReportDefinition
 * @param ops        array of op objects
 * @param resolveRef (ref) => {ok, id} | {ok:false, reason} — maps handles to UUIDs
 * @returns {{diff: string[], warnings: string[]}}
 * @throws {OpsError} when any op or invariant fails (definition may be partially mutated —
 *         callers must discard it, which they do: nothing is PUT on failure)
 */
export function applyOps(definition, ops, resolveRef = (ref) => ({ ok: true, id: ref })) {
  if (!Array.isArray(ops) || ops.length === 0) {
    throw new OpsError(['ops が空です。{"ops":[…]} の形式で指定してください。'])
  }
  const errors = []
  const diff = []

  const resolve = (ref, at) => {
    if (!ref) {
      errors.push(`${at}: elementId が必要です。`)
      return null
    }
    const r = resolveRef(ref)
    if (!r.ok) {
      errors.push(`${at}: ${r.reason}`)
      return null
    }
    const found = findElement(definition, r.id)
    if (!found) {
      errors.push(`${at}: 要素が見つかりません (${ref}${r.id !== ref ? ` → ${r.id}` : ''})`)
      return null
    }
    return found
  }

  for (const [i, op] of ops.entries()) {
    const at = `ops[${i}] ${op?.op ?? '(no op)'}`
    switch (op?.op) {
      case 'addElement': {
        const pageIndex = Number(op.pageIndex ?? 0)
        const page = (definition.pages ?? [])[pageIndex]
        if (!page) {
          errors.push(`${at}: page[${pageIndex}] が存在しません。`)
          break
        }
        const sections = page.sections ?? []
        const section = op.sectionId
          ? sections.find((s) => s.id === op.sectionId)
          : (sections.find((s) => s.sectionType === 'body') ?? sections[0])
        if (!section) {
          errors.push(`${at}: page[${pageIndex}] にセクションがありません。要素は sections[].elements に置きます。`)
          break
        }
        if (!op.element || typeof op.element !== 'object') {
          errors.push(`${at}: element オブジェクトが必要です。`)
          break
        }
        const el = normalizeElement(op.element)
        section.elements = section.elements ?? []
        section.elements.push(el)
        diff.push(`+ ${el.id.slice(0, 8)} ${el.type} @${el.position.x},${el.position.y} → page[${pageIndex}]/${section.sectionType}`)
        break
      }

      case 'updateElement': {
        const found = resolve(op.elementId, at)
        if (!found) break
        const patch = op.patch ?? {}
        for (const [k, v] of Object.entries(patch)) {
          const before = found.element[k]
          // style/position/size merge shallowly; everything else replaces.
          if (v && typeof v === 'object' && !Array.isArray(v) && found.element[k] && typeof found.element[k] === 'object') {
            Object.assign(found.element[k], v)
            diff.push(`~ ${op.elementId} ${k} ← ${JSON.stringify(v)}`)
          } else {
            found.element[k] = v
            diff.push(`~ ${op.elementId} ${k} ${JSON.stringify(before)} → ${JSON.stringify(v)}`)
          }
        }
        break
      }

      case 'removeElement': {
        const found = resolve(op.elementId, at)
        if (!found) break
        found.section.elements.splice(found.index, 1)
        diff.push(`- ${op.elementId} ${found.element.type}`)
        break
      }

      case 'moveElement': {
        const found = resolve(op.elementId, at)
        if (!found) break
        const el = found.element
        const before = `${el.position.x},${el.position.y},${el.size.width},${el.size.height}`
        if (op.x !== undefined) el.position.x = Number(op.x)
        if (op.y !== undefined) el.position.y = Number(op.y)
        if (op.width !== undefined) el.size.width = Number(op.width)
        if (op.height !== undefined) el.size.height = Number(op.height)
        if (op.toSectionId) {
          const target = allSections(definition).find(({ section }) => section.id === op.toSectionId)
          if (!target) {
            errors.push(`${at}: セクション ${op.toSectionId} が見つかりません。`)
            break
          }
          found.section.elements.splice(found.index, 1)
          target.section.elements = target.section.elements ?? []
          target.section.elements.push(el)
          diff.push(`→ ${op.elementId} section ${found.section.id.slice(0, 8)} → ${op.toSectionId.slice(0, 8)}`)
        }
        const after = `${el.position.x},${el.position.y},${el.size.width},${el.size.height}`
        if (before !== after) diff.push(`~ ${op.elementId} rect ${before} → ${after}`)
        break
      }

      case 'addPage': {
        const preset = PAPER_PRESETS[op.preset ?? 'A4P']
        if (!preset) {
          errors.push(`${at}: preset は ${Object.keys(PAPER_PRESETS).join('/')} のいずれかです。`)
          break
        }
        definition.pages = definition.pages ?? []
        const page = {
          id: randomUUID(),
          name: op.name ?? `ページ ${definition.pages.length + 1}`,
          background: '#ffffff',
          width: preset.width,
          height: preset.height,
          sections: [
            { id: randomUUID(), sectionType: 'body', height: preset.height, elements: [] },
          ],
        }
        const at_ = op.afterIndex === undefined ? definition.pages.length : Number(op.afterIndex) + 1
        definition.pages.splice(at_, 0, page)
        diff.push(`+ page[${at_}] ${page.name} ${preset.width}x${preset.height}mm`)
        break
      }

      case 'removePage': {
        const idx = Number(op.pageIndex)
        if (!Number.isInteger(idx) || !(definition.pages ?? [])[idx]) {
          errors.push(`${at}: page[${op.pageIndex}] が存在しません。`)
          break
        }
        const [removed] = definition.pages.splice(idx, 1)
        diff.push(`- page[${idx}] ${removed.name ?? ''}`)
        break
      }

      case 'setSchemaGroup': {
        const group = (definition?.schema?.groups ?? []).find((g) => g.dataKey === op.dataKey)
        if (!group) {
          errors.push(`${at}: スキーマグループ "${op.dataKey}" が見つかりません。`)
          break
        }
        Object.assign(group, op.patch ?? {})
        diff.push(`~ schema.${op.dataKey} ← ${JSON.stringify(op.patch ?? {})}`)
        break
      }

      case 'setSchemaField': {
        const group = (definition?.schema?.groups ?? []).find((g) => g.dataKey === op.dataKey)
        if (!group) {
          errors.push(`${at}: スキーマグループ "${op.dataKey}" が見つかりません。`)
          break
        }
        const field = (group.fields ?? []).find((f) => f.key === op.fieldKey)
        if (!field) {
          errors.push(`${at}: フィールド "${op.dataKey}.${op.fieldKey}" が見つかりません。`)
          break
        }
        Object.assign(field, op.patch ?? {})
        diff.push(`~ schema.${op.dataKey}.${op.fieldKey} ← ${JSON.stringify(op.patch ?? {})}`)
        break
      }

      case 'setRule': {
        const key = op.kind === 'validation' ? 'validationRules' : 'calculationRules'
        definition[key] = definition[key] ?? []
        const existing = op.ruleId ? definition[key].find((r) => r.id === op.ruleId) : null
        if (existing) {
          Object.assign(existing, op.patch ?? {})
          diff.push(`~ ${key}[${op.ruleId}] ← ${JSON.stringify(op.patch ?? {})}`)
        } else {
          const rule = { id: op.ruleId ?? randomUUID(), ...(op.patch ?? {}) }
          definition[key].push(rule)
          diff.push(`+ ${key}[${rule.id.slice(0, 8)}]`)
        }
        break
      }

      case 'setPointer': {
        const error = setPointer(definition, op.pointer, op.value)
        if (error) errors.push(`${at}: ${error}`)
        else diff.push(`~ ${op.pointer} ← ${JSON.stringify(op.value)}`)
        break
      }

      default:
        errors.push(`${at}: 未知の op です。使用可能: addElement, updateElement, removeElement, moveElement, addPage, removePage, setSchemaGroup, setSchemaField, setRule, setPointer`)
    }
  }

  if (errors.length > 0) throw new OpsError(errors)

  const { errors: invariantErrors, warnings } = checkInvariants(definition)
  if (invariantErrors.length > 0) throw new OpsError(invariantErrors)

  return { diff, warnings }
}
