/**
 * Regenerates schemas/report-definition.schema.json from the Zod schema, and
 * schemas/element-types.json from the ReportElement union (#415).
 *
 * Usage: npm run generate:schema
 * (runs via vite-node so path aliases and JSON imports resolve like the app)
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { buildReportDefinitionJsonSchema } from '../src/lib/schemas/jsonSchema'
import { ELEMENT_TYPES } from '../src/types/elementTypes'

const outPath = resolve(__dirname, '../schemas/report-definition.schema.json')
const schema = buildReportDefinitionJsonSchema()
writeFileSync(outPath, JSON.stringify(schema, null, 2) + '\n')
console.log(`wrote ${outPath}`)

// #415: machine-readable element-type list — consumed by the server's
// V2ElementParityMatrixTest so a frontend-added type fails the server build.
const typesPath = resolve(__dirname, '../schemas/element-types.json')
const typesJson = {
  $comment:
    'Generated by npm run generate:schema from src/types/elementTypes.ts (#415) — do not edit by hand. ' +
    'Compile-time assertions pin the list to the ReportElement union; ' +
    'src/types/elementTypes.test.ts pins this file to the list; ' +
    'server V2ElementParityMatrixTest reads it and fails when a type has no renderer/notes entry.',
  elementTypes: [...ELEMENT_TYPES],
}
writeFileSync(typesPath, JSON.stringify(typesJson, null, 2) + '\n')
console.log(`wrote ${typesPath}`)
